### ISSUE TITLE
Always use default value when stdin is pipe.

### ISSUE THREAD

**Issue by pyama86** [Songmu/prompter#6]
Hi! Songmu san!
Yattemasuka???

I have happened that always use default value when stdin is pipe.
```go
package main

import (
	"fmt"

	"github.com/Songmu/prompter"
)

func main() {

	if prompter.YesNo("example", false) {
		fmt.Println("say yes")
	}
}
```
```bash
% go run /tmp/main.go
example (yes/no) [no]: yes
say yes
% yes | go run /tmp/main.go
example (yes/no) [no]: % 
```
I think that the cause is like the code below.
https://github.com/Songmu/prompter/blob/master/prompter.go#L67

So I want to ask, what is the intention of this code? I want to discuss the amendment policy.

こんにちは！
prompter便利に利用させてもらってます！最高です！

darwinでの利用時にpipeだと常にデフォルトバリューが利用されるようで、yesコマンドが上手くう使えないので、上記の箇所のもとの意図を聞きたいです。

**Comment by Songmu** [comment]
This is a vexing issue.

I've merged https://github.com/Songmu/prompter/pull/8 for now.

This is what happens when stdin is not connected to the tty, it is considered as "not interactive" and uses the default value not the piped value. Yes, as you say, I don't also think this is an intuitive behavior.

However, in the first place, I don't think it's a good idea to give the value to prompt via a pipe. 

Prompts should only be used to interact with the user, and if you want to give input from stdin, you should take care of that in some other way.

For example, you could do the following

```
# Passed as a command line argument
echo "hoge" | xargs -I{} yourcmd --input={}

# When a specific environment variable is set, adopt it without prompting.
YOURCMD_INPUT=xxxxx yourcmd

# Provide an option to get the value from the stdin explicitly.
echo "xxxxx" | yourcmd --password-stdin
```

**Comment by pyama86** [comment]
I mostly agree.
I want to test including the prompt operation from user, and in that case, surrogate input using the yes command is useful.

I think it's good to have a dedicated option for testing as suggested, but it can be a bit confusing for normal use.
